Connect to spark-ui running on Driver Pod
aws/aws-emr-containers-best-practices pull request #16
Opened 2021-09-13 19:19 UTC by awsalialem

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-10-08 20:35 UTC, nithu0115 requested changes
Thanks for your contribution @awsalialem! Overall, PR looks good! Some minor comments...

2021-10-08 20:35 UTC, nithu0115 commented on content/debugging/docs/connect-spark-ui.md
> +To obtain more detail about their application or monitor their job execution, Spark application developers can connect to Spark-UI running on the Driver Pod.
Could you add a statement that, Spark UI (Spark history server) is packaged with EMR on EKS out of the box. Alternatively, if customers want to see Spark UI immediately after the driver is spun up, they can use `kubectl port-forward` route?

2021-10-08 20:35 UTC, nithu0115 commented on content/debugging/docs/connect-spark-ui.md
> +Once the job is submitted successfully, run `kubectl get pods -n <virtual-cluster-k8s-namespace> -w ` command to watch all the pods, until you observe the driver pod is in the "Running" state. The Dr
Could you add a pre-requisite section:
* AWS cli should be installed
* kubectl should be installed
* Customer should run `aws eks update-kubeconfig --name <cluster--name> --region <us-west-2> to download kubeconfig file and use currect context to talk to API server.

2021-10-09 21:23 UTC, awsalialem commented
Addressed the change requests, appreciate another review

2021-10-11 16:03 UTC, dacort requested changes
2 more minor revisions.

2021-10-11 16:03 UTC, dacort commented on content/debugging/docs/connect-spark-ui.md
> +* If this is the first time you are connecting to your EKS cluster from your machine, you should run `aws eks update-kubeconfig --name --region` to download kubeconfig file and use currect context to
Spelling.

```suggestion
* If this is the first time you are connecting to your EKS cluster from your machine, you should run `aws eks update-kubeconfig --name --region` to download kubeconfig file and use correct context to talk to API server.
```

2021-10-11 16:03 UTC, dacort commented on content/debugging/docs/connect-spark-ui.md
> +The result should as the following:
Grammar.
```suggestion
The result should be the following:
```

2021-10-12 18:06 UTC, awsalialem commented
Addressed the spelling errors

2021-10-19 23:01 UTC, dacort approved these changes

2022-06-14 18:55 UTC, merged