Secrets manager
aws/aws-emr-containers-best-practices pull request #29
Opened 2022-08-30 12:21 UTC by lmouhib

*Issue #, if available:*

*Description of changes:*
This PR add an example of how to use AWS secrets manager with EMR on EKS.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-08-30 18:07 UTC, dalbhanj requested changes
Hi @lmouhib thank you for this PR. Can you please make few minor changes as suggested? Thank you!

2022-08-30 18:07 UTC, dalbhanj commented on content/security/docs/spark/secrets.md
> +as environment are defined in clear in the template and Kubernets Secrets were not designed to securly store credentials.
as secrets are stored in clear text and any authorized user who has access to Kubernetes cluster with admin privileges can read those secrets. Storing secrets using Kubernetes secrets is also not secure because they are not encrypted and only base36 encoded.

2022-08-30 18:07 UTC, dalbhanj commented on content/security/docs/spark/secrets.md
> +The Secrets Store CSI Driver integrate with a secret store like AWS Secrets manager and mount the secrets as volume that can be accessed throught your code.
through your application code.

2022-08-30 18:07 UTC, dalbhanj commented on content/security/docs/spark/secrets.md
> +The `kubectl` command must be executed in the namespace of the where your job is going to be executed.
command must include the namespace where your job will be executed

2022-08-30 18:12 UTC, dalbhanj requested changes

2022-08-30 18:12 UTC, dalbhanj commented on content/security/docs/spark/secrets.md
> +
I'd add some info around making sure to have network path to RDS database and to configure RDS Security Group to allow IP subnet range of Spark application pods.

2022-08-30 18:28 UTC, lmouhib commented on content/security/docs/spark/secrets.md
> +as environment are defined in clear in the template and Kubernets Secrets were not designed to securly store credentials.
done

2022-09-09 16:51 UTC, dalbhanj approved these changes
lgtm

2022-09-09 16:51 UTC, merged