Update emr-containers.yaml - added patch
aws/aws-emr-containers-best-practices pull request #60
Opened 2024-10-17 22:38 UTC by tonytrivi

I was asked to make an edit, per an AWS customer ticket. I'm a technical writer. The change was proposed by a developer on the service team.

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-10-28 18:46 UTC, pthatchinamoorthy approved these changes

2024-10-28 18:50 UTC, pthatchinamoorthy requested changes
I think, `deletecollection` is needed for `persistentvolumeclaims`, starting 6.12

2024-10-28 23:44 UTC, melodyyangaws commented
please add the "deletecollection" to persistentvolumeclaims as well

2024-10-29 00:20 UTC, melodyyangaws approved these changes

2024-10-29 00:20 UTC, merged